/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt --output-dir=/home/salvo/ETH/github/LogGOPSim/simulator 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: goalsim [OPTIONS]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "      --version                 Print version and exit",
  "      --network-file=STRING     Input file for network (annotated dot format)",
  "      --network-pktsize=INT     Network packet size  (default=`64')",
  "      --network-maxcredits=INT  Switch buffer capacity  (default=`4096')",
  "      --network-ptime=INT       Switch packet's byte processing time\n                                  (default=`1')",
  "      --network-latency=INT     Link latency  (default=`2000')",
  "  -f, --filename=STRING         Prefix for the filenames which contain the\n                                  schedules",
  "      --save-mem                Map the schedules as MAP_SHARED to enable\n                                  processing of large schedule (larger than\n                                  main memory). This will invalidate the\n                                  schedules during simulation.  (default=off)",
  "  -V, --vizfile=STRING          Name of the output file for visualization data",
  "  -v, --verbose                 Enable more verbose output",
  "      --progress                print progress",
  "  -b, --batchmode               enable batchmode (never print detailed host\n                                  info)",
  "      --noise-trace=STRING      Read Noise from trace <file>",
  "      --noise-cosched           Co-schedule noise (use same starttime on all\n                                  processes)  (default=off)",
  "      --noise-time-mult=FLOAT   Noise trace time multiplier (default is ns)\n                                  (default=`1.0')",
  "  -L, --LogGOPS_L=INT           The latency parameter L in the LogGP model\n                                  (default=`2500')",
  "  -o, --LogGOPS_o=INT           The overhead parameter o in the LogGP model\n                                  (default=`1500')",
  "  -g, --LogGOPS_g=INT           The gap per message parameter g in the LogGP\n                                  model  (default=`1000')",
  "  -G, --LogGOPS_G=INT           The gap per byte parameter G in the LogGP model\n                                  (default=`6')",
  "  -S, --LogGOPS_S=INT           Datasize at which we change from eager to\n                                  rendezvous protocol  (default=`65535')",
  "  -O, --LogGOPS_O=INT           The overhead per byte in LogGOP  (default=`0')",
  "  -C, --LogGOPS_C=INT           P4: Time to transfer 1byte from the main memory\n                                  to the NIC memory  (default=`1')",
  "  -c, --LogGOPS_c=INT           P4: Time required from the NIC to process one\n                                  incoming message  (default=`100')",
  "      --sPIN_c_packet=INT       P4: Time required from the NIC to match one\n                                  packet but the first  (default=`10')",
  "      --gem5-conf-file=STRING   P4: GEM5 configuration file",
  "      --gem5-time-mult=INT      P4: GEM5 time multiplier (1 tick=1ps)\n                                  (default=`1000')",
  "      --gem5_o_hpu=INT          P4: overhead of sending network request from\n                                  HPU   (default=`0')",
  "      --gem5_o_nb_dma=INT       P4: overhead of non-blocking DMA requests\n                                  (default=`0')",
  "      --gem5_cas_failure_rate=INT\n                                P4: probability of CAS failure  (default=`10')",
  "      --DMA_L=INT               LogGP L for DMA  (default=`3')",
  "      --DMA_G=INT               LogGP G for DMA  (default=`0')",
  "      --DMA_g=INT               LogGP g for DMA  (default=`0')",
  "      --DMA_contention=INT      Contention for DMA  (default=`1')",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->network_file_given = 0 ;
  args_info->network_pktsize_given = 0 ;
  args_info->network_maxcredits_given = 0 ;
  args_info->network_ptime_given = 0 ;
  args_info->network_latency_given = 0 ;
  args_info->filename_given = 0 ;
  args_info->save_mem_given = 0 ;
  args_info->vizfile_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->progress_given = 0 ;
  args_info->batchmode_given = 0 ;
  args_info->noise_trace_given = 0 ;
  args_info->noise_cosched_given = 0 ;
  args_info->noise_time_mult_given = 0 ;
  args_info->LogGOPS_L_given = 0 ;
  args_info->LogGOPS_o_given = 0 ;
  args_info->LogGOPS_g_given = 0 ;
  args_info->LogGOPS_G_given = 0 ;
  args_info->LogGOPS_S_given = 0 ;
  args_info->LogGOPS_O_given = 0 ;
  args_info->LogGOPS_C_given = 0 ;
  args_info->LogGOPS_c_given = 0 ;
  args_info->sPIN_c_packet_given = 0 ;
  args_info->gem5_conf_file_given = 0 ;
  args_info->gem5_time_mult_given = 0 ;
  args_info->gem5_o_hpu_given = 0 ;
  args_info->gem5_o_nb_dma_given = 0 ;
  args_info->gem5_cas_failure_rate_given = 0 ;
  args_info->DMA_L_given = 0 ;
  args_info->DMA_G_given = 0 ;
  args_info->DMA_g_given = 0 ;
  args_info->DMA_contention_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->network_file_arg = NULL;
  args_info->network_file_orig = NULL;
  args_info->network_pktsize_arg = 64;
  args_info->network_pktsize_orig = NULL;
  args_info->network_maxcredits_arg = 4096;
  args_info->network_maxcredits_orig = NULL;
  args_info->network_ptime_arg = 1;
  args_info->network_ptime_orig = NULL;
  args_info->network_latency_arg = 2000;
  args_info->network_latency_orig = NULL;
  args_info->filename_arg = NULL;
  args_info->filename_orig = NULL;
  args_info->save_mem_flag = 0;
  args_info->vizfile_arg = NULL;
  args_info->vizfile_orig = NULL;
  args_info->noise_trace_arg = NULL;
  args_info->noise_trace_orig = NULL;
  args_info->noise_cosched_flag = 0;
  args_info->noise_time_mult_arg = 1.0;
  args_info->noise_time_mult_orig = NULL;
  args_info->LogGOPS_L_arg = 2500;
  args_info->LogGOPS_L_orig = NULL;
  args_info->LogGOPS_o_arg = 1500;
  args_info->LogGOPS_o_orig = NULL;
  args_info->LogGOPS_g_arg = 1000;
  args_info->LogGOPS_g_orig = NULL;
  args_info->LogGOPS_G_arg = 6;
  args_info->LogGOPS_G_orig = NULL;
  args_info->LogGOPS_S_arg = 65535;
  args_info->LogGOPS_S_orig = NULL;
  args_info->LogGOPS_O_arg = 0;
  args_info->LogGOPS_O_orig = NULL;
  args_info->LogGOPS_C_arg = 1;
  args_info->LogGOPS_C_orig = NULL;
  args_info->LogGOPS_c_arg = 100;
  args_info->LogGOPS_c_orig = NULL;
  args_info->sPIN_c_packet_arg = 10;
  args_info->sPIN_c_packet_orig = NULL;
  args_info->gem5_conf_file_arg = NULL;
  args_info->gem5_conf_file_orig = NULL;
  args_info->gem5_time_mult_arg = 1000;
  args_info->gem5_time_mult_orig = NULL;
  args_info->gem5_o_hpu_arg = 0;
  args_info->gem5_o_hpu_orig = NULL;
  args_info->gem5_o_nb_dma_arg = 0;
  args_info->gem5_o_nb_dma_orig = NULL;
  args_info->gem5_cas_failure_rate_arg = 10;
  args_info->gem5_cas_failure_rate_orig = NULL;
  args_info->DMA_L_arg = 3;
  args_info->DMA_L_orig = NULL;
  args_info->DMA_G_arg = 0;
  args_info->DMA_G_orig = NULL;
  args_info->DMA_g_arg = 0;
  args_info->DMA_g_orig = NULL;
  args_info->DMA_contention_arg = 1;
  args_info->DMA_contention_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->network_file_help = gengetopt_args_info_help[2] ;
  args_info->network_pktsize_help = gengetopt_args_info_help[3] ;
  args_info->network_maxcredits_help = gengetopt_args_info_help[4] ;
  args_info->network_ptime_help = gengetopt_args_info_help[5] ;
  args_info->network_latency_help = gengetopt_args_info_help[6] ;
  args_info->filename_help = gengetopt_args_info_help[7] ;
  args_info->save_mem_help = gengetopt_args_info_help[8] ;
  args_info->vizfile_help = gengetopt_args_info_help[9] ;
  args_info->verbose_help = gengetopt_args_info_help[10] ;
  args_info->progress_help = gengetopt_args_info_help[11] ;
  args_info->batchmode_help = gengetopt_args_info_help[12] ;
  args_info->noise_trace_help = gengetopt_args_info_help[13] ;
  args_info->noise_cosched_help = gengetopt_args_info_help[14] ;
  args_info->noise_time_mult_help = gengetopt_args_info_help[15] ;
  args_info->LogGOPS_L_help = gengetopt_args_info_help[16] ;
  args_info->LogGOPS_o_help = gengetopt_args_info_help[17] ;
  args_info->LogGOPS_g_help = gengetopt_args_info_help[18] ;
  args_info->LogGOPS_G_help = gengetopt_args_info_help[19] ;
  args_info->LogGOPS_S_help = gengetopt_args_info_help[20] ;
  args_info->LogGOPS_O_help = gengetopt_args_info_help[21] ;
  args_info->LogGOPS_C_help = gengetopt_args_info_help[22] ;
  args_info->LogGOPS_c_help = gengetopt_args_info_help[23] ;
  args_info->sPIN_c_packet_help = gengetopt_args_info_help[24] ;
  args_info->gem5_conf_file_help = gengetopt_args_info_help[25] ;
  args_info->gem5_time_mult_help = gengetopt_args_info_help[26] ;
  args_info->gem5_o_hpu_help = gengetopt_args_info_help[27] ;
  args_info->gem5_o_nb_dma_help = gengetopt_args_info_help[28] ;
  args_info->gem5_cas_failure_rate_help = gengetopt_args_info_help[29] ;
  args_info->DMA_L_help = gengetopt_args_info_help[30] ;
  args_info->DMA_G_help = gengetopt_args_info_help[31] ;
  args_info->DMA_g_help = gengetopt_args_info_help[32] ;
  args_info->DMA_contention_help = gengetopt_args_info_help[33] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->network_file_arg));
  free_string_field (&(args_info->network_file_orig));
  free_string_field (&(args_info->network_pktsize_orig));
  free_string_field (&(args_info->network_maxcredits_orig));
  free_string_field (&(args_info->network_ptime_orig));
  free_string_field (&(args_info->network_latency_orig));
  free_string_field (&(args_info->filename_arg));
  free_string_field (&(args_info->filename_orig));
  free_string_field (&(args_info->vizfile_arg));
  free_string_field (&(args_info->vizfile_orig));
  free_string_field (&(args_info->noise_trace_arg));
  free_string_field (&(args_info->noise_trace_orig));
  free_string_field (&(args_info->noise_time_mult_orig));
  free_string_field (&(args_info->LogGOPS_L_orig));
  free_string_field (&(args_info->LogGOPS_o_orig));
  free_string_field (&(args_info->LogGOPS_g_orig));
  free_string_field (&(args_info->LogGOPS_G_orig));
  free_string_field (&(args_info->LogGOPS_S_orig));
  free_string_field (&(args_info->LogGOPS_O_orig));
  free_string_field (&(args_info->LogGOPS_C_orig));
  free_string_field (&(args_info->LogGOPS_c_orig));
  free_string_field (&(args_info->sPIN_c_packet_orig));
  free_string_field (&(args_info->gem5_conf_file_arg));
  free_string_field (&(args_info->gem5_conf_file_orig));
  free_string_field (&(args_info->gem5_time_mult_orig));
  free_string_field (&(args_info->gem5_o_hpu_orig));
  free_string_field (&(args_info->gem5_o_nb_dma_orig));
  free_string_field (&(args_info->gem5_cas_failure_rate_orig));
  free_string_field (&(args_info->DMA_L_orig));
  free_string_field (&(args_info->DMA_G_orig));
  free_string_field (&(args_info->DMA_g_orig));
  free_string_field (&(args_info->DMA_contention_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->network_file_given)
    write_into_file(outfile, "network-file", args_info->network_file_orig, 0);
  if (args_info->network_pktsize_given)
    write_into_file(outfile, "network-pktsize", args_info->network_pktsize_orig, 0);
  if (args_info->network_maxcredits_given)
    write_into_file(outfile, "network-maxcredits", args_info->network_maxcredits_orig, 0);
  if (args_info->network_ptime_given)
    write_into_file(outfile, "network-ptime", args_info->network_ptime_orig, 0);
  if (args_info->network_latency_given)
    write_into_file(outfile, "network-latency", args_info->network_latency_orig, 0);
  if (args_info->filename_given)
    write_into_file(outfile, "filename", args_info->filename_orig, 0);
  if (args_info->save_mem_given)
    write_into_file(outfile, "save-mem", 0, 0 );
  if (args_info->vizfile_given)
    write_into_file(outfile, "vizfile", args_info->vizfile_orig, 0);
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", 0, 0 );
  if (args_info->progress_given)
    write_into_file(outfile, "progress", 0, 0 );
  if (args_info->batchmode_given)
    write_into_file(outfile, "batchmode", 0, 0 );
  if (args_info->noise_trace_given)
    write_into_file(outfile, "noise-trace", args_info->noise_trace_orig, 0);
  if (args_info->noise_cosched_given)
    write_into_file(outfile, "noise-cosched", 0, 0 );
  if (args_info->noise_time_mult_given)
    write_into_file(outfile, "noise-time-mult", args_info->noise_time_mult_orig, 0);
  if (args_info->LogGOPS_L_given)
    write_into_file(outfile, "LogGOPS_L", args_info->LogGOPS_L_orig, 0);
  if (args_info->LogGOPS_o_given)
    write_into_file(outfile, "LogGOPS_o", args_info->LogGOPS_o_orig, 0);
  if (args_info->LogGOPS_g_given)
    write_into_file(outfile, "LogGOPS_g", args_info->LogGOPS_g_orig, 0);
  if (args_info->LogGOPS_G_given)
    write_into_file(outfile, "LogGOPS_G", args_info->LogGOPS_G_orig, 0);
  if (args_info->LogGOPS_S_given)
    write_into_file(outfile, "LogGOPS_S", args_info->LogGOPS_S_orig, 0);
  if (args_info->LogGOPS_O_given)
    write_into_file(outfile, "LogGOPS_O", args_info->LogGOPS_O_orig, 0);
  if (args_info->LogGOPS_C_given)
    write_into_file(outfile, "LogGOPS_C", args_info->LogGOPS_C_orig, 0);
  if (args_info->LogGOPS_c_given)
    write_into_file(outfile, "LogGOPS_c", args_info->LogGOPS_c_orig, 0);
  if (args_info->sPIN_c_packet_given)
    write_into_file(outfile, "sPIN_c_packet", args_info->sPIN_c_packet_orig, 0);
  if (args_info->gem5_conf_file_given)
    write_into_file(outfile, "gem5-conf-file", args_info->gem5_conf_file_orig, 0);
  if (args_info->gem5_time_mult_given)
    write_into_file(outfile, "gem5-time-mult", args_info->gem5_time_mult_orig, 0);
  if (args_info->gem5_o_hpu_given)
    write_into_file(outfile, "gem5_o_hpu", args_info->gem5_o_hpu_orig, 0);
  if (args_info->gem5_o_nb_dma_given)
    write_into_file(outfile, "gem5_o_nb_dma", args_info->gem5_o_nb_dma_orig, 0);
  if (args_info->gem5_cas_failure_rate_given)
    write_into_file(outfile, "gem5_cas_failure_rate", args_info->gem5_cas_failure_rate_orig, 0);
  if (args_info->DMA_L_given)
    write_into_file(outfile, "DMA_L", args_info->DMA_L_orig, 0);
  if (args_info->DMA_G_given)
    write_into_file(outfile, "DMA_G", args_info->DMA_G_orig, 0);
  if (args_info->DMA_g_given)
    write_into_file(outfile, "DMA_g", args_info->DMA_g_orig, 0);
  if (args_info->DMA_contention_given)
    write_into_file(outfile, "DMA_contention", args_info->DMA_contention_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->filename_given)
    {
      fprintf (stderr, "%s: '--filename' ('-f') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 0 },
        { "network-file",	1, NULL, 0 },
        { "network-pktsize",	1, NULL, 0 },
        { "network-maxcredits",	1, NULL, 0 },
        { "network-ptime",	1, NULL, 0 },
        { "network-latency",	1, NULL, 0 },
        { "filename",	1, NULL, 'f' },
        { "save-mem",	0, NULL, 0 },
        { "vizfile",	1, NULL, 'V' },
        { "verbose",	0, NULL, 'v' },
        { "progress",	0, NULL, 0 },
        { "batchmode",	0, NULL, 'b' },
        { "noise-trace",	1, NULL, 0 },
        { "noise-cosched",	0, NULL, 0 },
        { "noise-time-mult",	1, NULL, 0 },
        { "LogGOPS_L",	1, NULL, 'L' },
        { "LogGOPS_o",	1, NULL, 'o' },
        { "LogGOPS_g",	1, NULL, 'g' },
        { "LogGOPS_G",	1, NULL, 'G' },
        { "LogGOPS_S",	1, NULL, 'S' },
        { "LogGOPS_O",	1, NULL, 'O' },
        { "LogGOPS_C",	1, NULL, 'C' },
        { "LogGOPS_c",	1, NULL, 'c' },
        { "sPIN_c_packet",	1, NULL, 0 },
        { "gem5-conf-file",	1, NULL, 0 },
        { "gem5-time-mult",	1, NULL, 0 },
        { "gem5_o_hpu",	1, NULL, 0 },
        { "gem5_o_nb_dma",	1, NULL, 0 },
        { "gem5_cas_failure_rate",	1, NULL, 0 },
        { "DMA_L",	1, NULL, 0 },
        { "DMA_G",	1, NULL, 0 },
        { "DMA_g",	1, NULL, 0 },
        { "DMA_contention",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hf:V:vbL:o:g:G:S:O:C:c:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'f':	/* Prefix for the filenames which contain the schedules.  */
        
        
          if (update_arg( (void *)&(args_info->filename_arg), 
               &(args_info->filename_orig), &(args_info->filename_given),
              &(local_args_info.filename_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "filename", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'V':	/* Name of the output file for visualization data.  */
        
        
          if (update_arg( (void *)&(args_info->vizfile_arg), 
               &(args_info->vizfile_orig), &(args_info->vizfile_given),
              &(local_args_info.vizfile_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "vizfile", 'V',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* Enable more verbose output.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "verbose", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* enable batchmode (never print detailed host info).  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->batchmode_given),
              &(local_args_info.batchmode_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "batchmode", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'L':	/* The latency parameter L in the LogGP model.  */
        
        
          if (update_arg( (void *)&(args_info->LogGOPS_L_arg), 
               &(args_info->LogGOPS_L_orig), &(args_info->LogGOPS_L_given),
              &(local_args_info.LogGOPS_L_given), optarg, 0, "2500", ARG_INT,
              check_ambiguity, override, 0, 0,
              "LogGOPS_L", 'L',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* The overhead parameter o in the LogGP model.  */
        
        
          if (update_arg( (void *)&(args_info->LogGOPS_o_arg), 
               &(args_info->LogGOPS_o_orig), &(args_info->LogGOPS_o_given),
              &(local_args_info.LogGOPS_o_given), optarg, 0, "1500", ARG_INT,
              check_ambiguity, override, 0, 0,
              "LogGOPS_o", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* The gap per message parameter g in the LogGP model.  */
        
        
          if (update_arg( (void *)&(args_info->LogGOPS_g_arg), 
               &(args_info->LogGOPS_g_orig), &(args_info->LogGOPS_g_given),
              &(local_args_info.LogGOPS_g_given), optarg, 0, "1000", ARG_INT,
              check_ambiguity, override, 0, 0,
              "LogGOPS_g", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'G':	/* The gap per byte parameter G in the LogGP model.  */
        
        
          if (update_arg( (void *)&(args_info->LogGOPS_G_arg), 
               &(args_info->LogGOPS_G_orig), &(args_info->LogGOPS_G_given),
              &(local_args_info.LogGOPS_G_given), optarg, 0, "6", ARG_INT,
              check_ambiguity, override, 0, 0,
              "LogGOPS_G", 'G',
              additional_error))
            goto failure;
        
          break;
        case 'S':	/* Datasize at which we change from eager to rendezvous protocol.  */
        
        
          if (update_arg( (void *)&(args_info->LogGOPS_S_arg), 
               &(args_info->LogGOPS_S_orig), &(args_info->LogGOPS_S_given),
              &(local_args_info.LogGOPS_S_given), optarg, 0, "65535", ARG_INT,
              check_ambiguity, override, 0, 0,
              "LogGOPS_S", 'S',
              additional_error))
            goto failure;
        
          break;
        case 'O':	/* The overhead per byte in LogGOP.  */
        
        
          if (update_arg( (void *)&(args_info->LogGOPS_O_arg), 
               &(args_info->LogGOPS_O_orig), &(args_info->LogGOPS_O_given),
              &(local_args_info.LogGOPS_O_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "LogGOPS_O", 'O',
              additional_error))
            goto failure;
        
          break;
        case 'C':	/* P4: Time to transfer 1byte from the main memory to the NIC memory.  */
        
        
          if (update_arg( (void *)&(args_info->LogGOPS_C_arg), 
               &(args_info->LogGOPS_C_orig), &(args_info->LogGOPS_C_given),
              &(local_args_info.LogGOPS_C_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "LogGOPS_C", 'C',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* P4: Time required from the NIC to process one incoming message.  */
        
        
          if (update_arg( (void *)&(args_info->LogGOPS_c_arg), 
               &(args_info->LogGOPS_c_orig), &(args_info->LogGOPS_c_given),
              &(local_args_info.LogGOPS_c_given), optarg, 0, "100", ARG_INT,
              check_ambiguity, override, 0, 0,
              "LogGOPS_c", 'c',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          if (strcmp (long_options[option_index].name, "version") == 0) {
            cmdline_parser_print_version ();
            cmdline_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

          /* Input file for network (annotated dot format).  */
          if (strcmp (long_options[option_index].name, "network-file") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->network_file_arg), 
                 &(args_info->network_file_orig), &(args_info->network_file_given),
                &(local_args_info.network_file_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "network-file", '-',
                additional_error))
              goto failure;
          
          }
          /* Network packet size.  */
          else if (strcmp (long_options[option_index].name, "network-pktsize") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->network_pktsize_arg), 
                 &(args_info->network_pktsize_orig), &(args_info->network_pktsize_given),
                &(local_args_info.network_pktsize_given), optarg, 0, "64", ARG_INT,
                check_ambiguity, override, 0, 0,
                "network-pktsize", '-',
                additional_error))
              goto failure;
          
          }
          /* Switch buffer capacity.  */
          else if (strcmp (long_options[option_index].name, "network-maxcredits") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->network_maxcredits_arg), 
                 &(args_info->network_maxcredits_orig), &(args_info->network_maxcredits_given),
                &(local_args_info.network_maxcredits_given), optarg, 0, "4096", ARG_INT,
                check_ambiguity, override, 0, 0,
                "network-maxcredits", '-',
                additional_error))
              goto failure;
          
          }
          /* Switch packet's byte processing time.  */
          else if (strcmp (long_options[option_index].name, "network-ptime") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->network_ptime_arg), 
                 &(args_info->network_ptime_orig), &(args_info->network_ptime_given),
                &(local_args_info.network_ptime_given), optarg, 0, "1", ARG_INT,
                check_ambiguity, override, 0, 0,
                "network-ptime", '-',
                additional_error))
              goto failure;
          
          }
          /* Link latency.  */
          else if (strcmp (long_options[option_index].name, "network-latency") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->network_latency_arg), 
                 &(args_info->network_latency_orig), &(args_info->network_latency_given),
                &(local_args_info.network_latency_given), optarg, 0, "2000", ARG_INT,
                check_ambiguity, override, 0, 0,
                "network-latency", '-',
                additional_error))
              goto failure;
          
          }
          /* Map the schedules as MAP_SHARED to enable processing of large schedule (larger than main memory). This will invalidate the schedules during simulation..  */
          else if (strcmp (long_options[option_index].name, "save-mem") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->save_mem_flag), 0, &(args_info->save_mem_given),
                &(local_args_info.save_mem_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "save-mem", '-',
                additional_error))
              goto failure;
          
          }
          /* print progress.  */
          else if (strcmp (long_options[option_index].name, "progress") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->progress_given),
                &(local_args_info.progress_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "progress", '-',
                additional_error))
              goto failure;
          
          }
          /* Read Noise from trace <file>.  */
          else if (strcmp (long_options[option_index].name, "noise-trace") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->noise_trace_arg), 
                 &(args_info->noise_trace_orig), &(args_info->noise_trace_given),
                &(local_args_info.noise_trace_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "noise-trace", '-',
                additional_error))
              goto failure;
          
          }
          /* Co-schedule noise (use same starttime on all processes).  */
          else if (strcmp (long_options[option_index].name, "noise-cosched") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->noise_cosched_flag), 0, &(args_info->noise_cosched_given),
                &(local_args_info.noise_cosched_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "noise-cosched", '-',
                additional_error))
              goto failure;
          
          }
          /* Noise trace time multiplier (default is ns).  */
          else if (strcmp (long_options[option_index].name, "noise-time-mult") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->noise_time_mult_arg), 
                 &(args_info->noise_time_mult_orig), &(args_info->noise_time_mult_given),
                &(local_args_info.noise_time_mult_given), optarg, 0, "1.0", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "noise-time-mult", '-',
                additional_error))
              goto failure;
          
          }
          /* P4: Time required from the NIC to match one packet but the first.  */
          else if (strcmp (long_options[option_index].name, "sPIN_c_packet") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->sPIN_c_packet_arg), 
                 &(args_info->sPIN_c_packet_orig), &(args_info->sPIN_c_packet_given),
                &(local_args_info.sPIN_c_packet_given), optarg, 0, "10", ARG_INT,
                check_ambiguity, override, 0, 0,
                "sPIN_c_packet", '-',
                additional_error))
              goto failure;
          
          }
          /* P4: GEM5 configuration file.  */
          else if (strcmp (long_options[option_index].name, "gem5-conf-file") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->gem5_conf_file_arg), 
                 &(args_info->gem5_conf_file_orig), &(args_info->gem5_conf_file_given),
                &(local_args_info.gem5_conf_file_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "gem5-conf-file", '-',
                additional_error))
              goto failure;
          
          }
          /* P4: GEM5 time multiplier (1 tick=1ps).  */
          else if (strcmp (long_options[option_index].name, "gem5-time-mult") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->gem5_time_mult_arg), 
                 &(args_info->gem5_time_mult_orig), &(args_info->gem5_time_mult_given),
                &(local_args_info.gem5_time_mult_given), optarg, 0, "1000", ARG_INT,
                check_ambiguity, override, 0, 0,
                "gem5-time-mult", '-',
                additional_error))
              goto failure;
          
          }
          /* P4: overhead of sending network request from HPU .  */
          else if (strcmp (long_options[option_index].name, "gem5_o_hpu") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->gem5_o_hpu_arg), 
                 &(args_info->gem5_o_hpu_orig), &(args_info->gem5_o_hpu_given),
                &(local_args_info.gem5_o_hpu_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "gem5_o_hpu", '-',
                additional_error))
              goto failure;
          
          }
          /* P4: overhead of non-blocking DMA requests.  */
          else if (strcmp (long_options[option_index].name, "gem5_o_nb_dma") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->gem5_o_nb_dma_arg), 
                 &(args_info->gem5_o_nb_dma_orig), &(args_info->gem5_o_nb_dma_given),
                &(local_args_info.gem5_o_nb_dma_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "gem5_o_nb_dma", '-',
                additional_error))
              goto failure;
          
          }
          /* P4: probability of CAS failure.  */
          else if (strcmp (long_options[option_index].name, "gem5_cas_failure_rate") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->gem5_cas_failure_rate_arg), 
                 &(args_info->gem5_cas_failure_rate_orig), &(args_info->gem5_cas_failure_rate_given),
                &(local_args_info.gem5_cas_failure_rate_given), optarg, 0, "10", ARG_INT,
                check_ambiguity, override, 0, 0,
                "gem5_cas_failure_rate", '-',
                additional_error))
              goto failure;
          
          }
          /* LogGP L for DMA.  */
          else if (strcmp (long_options[option_index].name, "DMA_L") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->DMA_L_arg), 
                 &(args_info->DMA_L_orig), &(args_info->DMA_L_given),
                &(local_args_info.DMA_L_given), optarg, 0, "3", ARG_INT,
                check_ambiguity, override, 0, 0,
                "DMA_L", '-',
                additional_error))
              goto failure;
          
          }
          /* LogGP G for DMA.  */
          else if (strcmp (long_options[option_index].name, "DMA_G") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->DMA_G_arg), 
                 &(args_info->DMA_G_orig), &(args_info->DMA_G_given),
                &(local_args_info.DMA_G_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "DMA_G", '-',
                additional_error))
              goto failure;
          
          }
          /* LogGP g for DMA.  */
          else if (strcmp (long_options[option_index].name, "DMA_g") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->DMA_g_arg), 
                 &(args_info->DMA_g_orig), &(args_info->DMA_g_given),
                &(local_args_info.DMA_g_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "DMA_g", '-',
                additional_error))
              goto failure;
          
          }
          /* Contention for DMA.  */
          else if (strcmp (long_options[option_index].name, "DMA_contention") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->DMA_contention_arg), 
                 &(args_info->DMA_contention_orig), &(args_info->DMA_contention_given),
                &(local_args_info.DMA_contention_given), optarg, 0, "1", ARG_INT,
                check_ambiguity, override, 0, 0,
                "DMA_contention", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
